name: All Stack Deployment

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install Server Side Dependencies
        working-directory: ./server
        run: npm install
      - name: Deploy to AWS
        working-directory: ./server
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
        run: npm run cdk -- deploy --require-approval never
