name: FrontEnd Deployment

on:
  push:
    branches:
      - master
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  build:
    environment: deployment
    runs-on: ubuntu-latest
    if: ${{ !contains(toJson(github.event_name.push.changed_files) , 'server/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Build
        working-directory: ./client
        run: npm run build
  deploy:
    environment: deployment
    needs: build
    runs-on: ubuntu-latest
    if: ${{ !contains(toJson(github.event_name.push.changed_files) , 'server/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies in client
        working-directory: ./client
        run: npm install
      - name: Install dependencies in server
        working-directory: ./server
        run: npm install
      - name: Deploy FrontEnd
        working-directory: ./server
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          FRONTEND_BUILD_OUT_DIR_PATH: ${{ vars.FRONTEND_BUILD_OUT_DIR_PATH }}
        run: npm run cdk -- deploy DeployStack --require-approval never
