name: Deploy All Stack to AWS Using AWS CDK

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install Server Side Dependencies
        working-directory: ./server
        run: npm install
      - name: Deploy to AWS
        working-directory: ./server
        run: npm run cdk -- deploy --require-approval never
