name: ESLint CDK Check

on:
  pull_request:
    paths:
      - 'cdk/**'

jobs:
  eslint-cdk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
    - name: Install CDK dependencies
      working-directory: cdk
      run: npm install
    - name: ESLint CDK
      working-directory: cdk
      run: npm run eslint -- . --ext .js,.jsx,.ts,.tsx
