name: Test Server Side Check

on:
  pull_request:

jobs:
  test-server-side:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
    - name: Install Server Side dependencies
      working-directory: server
      run: npm install
    - name: Test Server Side
      working-directory: server
      run: npm run test
