name: Test Server Side Check

on:
  pull_request:
    paths:
      - 'server/**'

jobs:
  test-cdk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
    - name: Install CDK dependencies
      working-directory: cdk
      run: npm install
    - name: Test CDK
      working-directory: cdk
      run: npm run test
